name: ColinPizey
favicon: null
layout_spectrum: 0.6462014843709767
typography_spectrum: 0.07447347231209278
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8405849502887577
  lightness: 0.8691518465057015
  saturation: 0.041012464091181755
  rhythmicContrast: 0.44203435885719955
purpose: []
